# Generated by Django 4.0.5 on 2022-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category2',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
